### ISSUE TITLE
Errors following update to HomeAssistant 2023.8

### ISSUE THREAD

**Issue by mamdavem** [pdw-mb/tsmart_ha#7] opened 2023-08-04 10:23 UTC
Errors following update to HomeAssistant 2023.8 I'm getting the errors

Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:619
Integration: Binary sensor (documentation, issues)
First occurred: 11:02:01 AM (2 occurrences)
Last logged: 11:02:01 AM

Error adding entities for domain binary_sensor with platform t_smart
Error while setting up t_smart platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'name_by_user'

and 

Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:619
Integration: Climate (documentation, issues)
First occurred: 11:02:01 AM (2 occurrences)
Last logged: 11:02:01 AM

Error adding entities for domain climate with platform t_smart
Error while setting up t_smart platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'name_by_user'

**Comment by pdw-mb** [comment] 2023-08-06 07:08
Duplicate of #5 fixed in 0.3.0

**Closed by pdw-mb** 2023-08-06 07:08 UTC
