### ISSUE TITLE
Entities not working

### ISSUE THREAD

**Issue by naigle** [pdw-mb/tsmart_ha#8] opened 2023-08-05 19:54 UTC
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'name_by_user'
2023-08-05 20:19:50.896 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up t_smart platform for binary_sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 370, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
device = dev_reg.async_get(self.hass).async_get_or_create(

Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:619
Integration: Binary Sensor (documentation, issues)
First occurred: 20:19:50 (2 occurrences)
Last logged: 20:19:50

Error adding entities for domain binary_sensor with platform t_smart
Error while setting up t_smart platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'name_by_user'

Home Assistant 2023.8.1 (also happened in 2023.8.0)
T Smart firmware 1.9.96

**Comment by pdw-mb** [comment] 2023-08-06 07:07
Duplicate of #5.

Fixed in release 0.3.0.

**Closed by pdw-mb** 2023-08-06 07:07 UTC
